In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [5]:
data=pd.read_csv('/Users/sruthi./Downloads/student-mat.csv')
print(data.head)

<bound method NDFrame.head of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freet

In [10]:
data=data[["G1","G2","G3","failures", "studytime", "absences"]]
predict="G3"

#Now split the data
x=np.array(data.drop([predict],axis=1))
y=np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain,xtest, ytrain, ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
linear_regression=LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy= linear_regression.score(xtest,ytest)
print(accuracy)


0.7821754247320556


In [16]:
predictions=linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x],xtest[x],[ytest[x]])
    

[[12.70478596 18.6925959   6.01113762  3.42583945 18.6925959 ]
 [12.70478596 12.70478596  6.01113762  3.42583945  7.87300271]
 [ 7.10011213  7.22885591  8.52243043  3.42583945 14.95294333]
 ...
 [14.95294333  7.22885591  8.52243043 12.20306263  8.52243043]
 [ 6.26901605 13.65241561  6.01113762 12.20306263  6.01113762]
 [ 7.22885591 12.6388124   6.01113762 12.20306263 12.70478596]] [[[12 13  0  2  0]
  [19 18  0  2  2]
  [ 8  8  3  1  2]
  [ 3  5  1  2  8]
  [19 18  0  2  2]]

 [[12 13  0  2  0]
  [12 13  0  2  0]
  [ 8  8  3  1  2]
  [ 3  5  1  2  8]
  [ 9  9  2  2 11]]

 [[ 9  7  0  2 18]
  [ 8  8  0  2  0]
  [ 8  9  0  2  8]
  [ 3  5  1  2  8]
  [14 15  0  2  0]]

 ...

 [[14 15  0  2  0]
  [ 8  8  0  2  0]
  [ 8  9  0  2  8]
  [14 12  0  1  3]
  [ 8  9  0  2  8]]

 [[ 7  7  0  3  6]
  [12 14  0  3  1]
  [ 8  8  3  1  2]
  [14 12  0  1  3]
  [ 8  8  3  1  2]]

 [[ 8  8  0  2  0]
  [11 13  0  2  2]
  [ 8  8  3  1  2]
  [14 12  0  1  3]
  [12 13  0  2  0]]] [array([[13, 18, 10,  5, 18]